name: cumilla_go
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  path: ^1.9.0
  sqflite_common_ffi: ^2.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png


dev_dependencies:

  flutter_test:

    sdk: flutter
  flutter_lints: ^5.0.0

