name: cumilla_go
description: A Flutter app for Cumilla City

environment:
  sdk: ">=2.12.0 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/places.json

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+3
  path_provider: ^2.0.10
  json_annotation: ^4.7.0
  path: ^1.8.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0 